routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('show');



Auth::routes();

Route::middleware('auth')->prefix('administrator')->group(function (){
    Route::get('/admin', 'AdminController@index')->name('admin');
    Route::resource('/Contact','ContactController');
    Route::resource('/Gallery','GalleryController');
    Route::resource('/News','NewsController');
    Route::resource('/Slider','SliderController');
    Route::resource('/Setting','SettingController');
    Route::resource('/About','AboutController');
});

Route::post('/insertContact','ContactController@store')->name('Contact.Data');

resources/views/admin/index.blade.php
@extends('layouts.layout')
@section('css')
    <title>پنل کاربری</title>
@endsection
@section('content')
    <!-- menu -->
    <section class="container-fluid ">
        <section class="menu ">
            <section class="row">
                <section class="col-12 ">
                    <nav class="navbar bg-warning  navbar-expand-sm fixed-top mr-3 ml-3 ">
                        <section class="container-fluid ">
                            <button class="navbar-toggler bg-primary fa fa-list " style="color: #c69500" data-toggle="collapse" data-target="#myToggleNav">

                            </button>
                            <section class="collapse navbar-collapse menuco " id="myToggleNav">
                                <section class="navbar-nav w-100 justify-content-start flex-sm-row-reverse text-center">
                                    <section class="dropdown">
                                        <a href="javascript;" class="nav-link nav-item dropdown-toggle" data-toggle="dropdown">تنظیمات</a>
                                        <section class="dropdown-menu">
                                            <a href="{{ route('Setting.index') }}" class="dropdown-item text-right">نمایش</a>
                                            <a href="{{ route('Setting.create') }}" class="dropdown-item text-right"> اضافه کردن</a>
                                        </section>
                                    </section>
                                    <section class="dropdown">
                                        <a href="javascript;" class="nav-link nav-item dropdown-toggle" data-toggle="dropdown">اخبار</a>
                                        <section class="dropdown-menu">
                                            <a href="{{ route('News.index') }}" class="dropdown-item text-right">نمایش</a>
                                            <a href="{{ route('News.create') }}" class="dropdown-item text-right"> اضافه کردن</a>
                                        </section>
                                    </section>
                                    <section class="dropdown">
                                        <a href="javascript;" class="nav-link nav-item dropdown-toggle" data-toggle="dropdown">اسلایدر</a>
                                        <section class="dropdown-menu">
                                            <a href="{{ route('Slider.index') }}" class="dropdown-item text-right"> نمایش</a>
                                            <a href="{{route('Slider.create')}}" class="dropdown-item text-right"> اضافه کردن</a>
                                        </section>
                                    </section>
                                    <section class="dropdown">
                                        <a href="javascript;" class="nav-link nav-item dropdown-toggle" data-toggle="dropdown">گالری</a>
                                        <section class="dropdown-menu">
                                            <a href="{{ route('Gallery.index') }}" class="dropdown-item text-right"> نمایش</a>
                                            <a href="{{ route('Gallery.create') }}" class="dropdown-item text-right"> اضافه کردن</a>
                                        </section>
                                    </section>
                                    <section class="dropdown">
                                        <a href="javascript;" class="nav-link nav-item dropdown-toggle" data-toggle="dropdown">ارتباط با ما</a>
                                        <section class="dropdown-menu">
                                            <a href="{{ route('Contact.index') }}" class="dropdown-item text-right"> نمایش</a>
                                            <a href="{{ route('Contact.create') }}" class="dropdown-item text-right"> اضافه کردن</a>
                                        </section>
                                    </section>

                                    <section class="dropdown">
                                        <a href="javascript;" class="nav-link nav-item dropdown-toggle" data-toggle="dropdown">درباره ما</a>
                                        <section class="dropdown-menu">
                                            <a href="{{ route('About.index') }}" class="dropdown-item text-right"> نمایش</a>
                                            <a href="{{ route('About.create') }}" class="dropdown-item text-right"> اضافه کردن</a>
                                        </section>
                                    </section>

                                        <a href="{{route('show')}}" class="nav-link nav-item-item" target="_blank" >وب سایت</a>


                                    <a class="nav-link nav-item-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('خروج') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </section>
                            </section>
                        </section>

                    </nav>
                </section>

            </section>
        </section>
    </section>
    <!-- end menu -->
    <br><br><br>


    <!-- footer -->

    <section class="container-fluid ">
        <section class="row ">
            <section class=" col-8 offset-2 mt-3">
                <footer class="text-dark text-center">
                    <hr>
                    <p>Copyright &copy; 2019 Blessing.com<p>
                </footer>
            </section>
        </section>
    </section>
    <!-- end footer -->
@endsection
@section('js')

@endsection

resources/views/admin/login.blade.php
@extends('layouts.layout')
@section('css')
    <title>صفحه ورود</title>
@endsection
@section('content')
    <body class="httm">
    <section class="container-fluid">
        <section class="row">
            <section class="col-8 offset-2 mt-5">
                <header class="text-center text-primary">
                    <h1>Blessing</h1>
                </header>
            </section>
        </section>
    </section>
    <section class="container-fluid">
        <section class="content">
            <section class="row">
                <section class="col-8 offset-2 mt-3 ">
                    <section class=" jumbotron jumcolor ">
                        <section class="text-right">
                            <form action="" method="">
                                <input type="hidden" name="order" value="login">
                                <section class="form-group ">
                                    <label for="username"><h5>نام کاربری </h5></label>
                                    <input type="text" id="username" name="username" class="form-control pr-3" required="required">
                                </section>
                                <section class="form-group">
                                    <label for="password"><h5>رمز عبور </h5></label>
                                    <input type="text" id="password" name="password" class="form-control pr-3" required="required">
                                </section>
                                <section class="form-group">
                                    <img  src="gd.php"  class="d-inline-flex" />
                                    <label for="password" class="d-inline-flex"><h5>کد را وارد کنید </h5></label>
                                    <input type="text" name="code" class="form-control " required="required">
                                </section>
                                <button type="submit" class="btn btn-primary btn-block">ورود</button>
                                <section class=" mt-4 text-center">
                                    <p>کاربر جدید هستید؟ <a href="register.php">ثبت نام</a> </p>
                                </section>

                            </form>
                        </section>
                    </section>
                </section>
            </section>
        </section>
    </section>
    <hr>
    <section class="container-fluid ">
        <section class="row ">
            <section class=" col-8 offset-2 mt-3">
                <footer class="text-dark text-center">
                    <p>Copyright &copy; 2019 Blessing.com<p>
                </footer>
            </section>
        </section>
    </section>
@endsection
@section('js')

@endsection

resources/views/admin/register.blade.php
@extends('layouts.layout')
@section('css')
    <title>صفحه ثبت نام</title>
@endsection
@section('content')
    <section class="container-fluid">
        <section class="row">
            <section class="col-8 offset-2 mt-5">
                <header class="text-center text-primary">
                    <h1>Blessing</h1>
                </header>
            </section>
        </section>
    </section>
    <section class="container-fluid">
        <section class="content">
            <section class="row">
                <section class="col-8 offset-2 mt-3 ">
                    <section class=" jumbotron jumcolor ">
                        <section class="text-right">
                            <form action="" method="">
                                <input type="hidden" name="order" value="register">
                                <section class="form-group ">
                                    <label for="username"><h5>نام کاربری </h5></label>
                                    <input type="text" id="username" name="username" class="form-control pr-2" required="required">
                                </section>
                                <section class="form-group ">
                                    <label for="email"><h5>ایمیل </h5></label>
                                    <input type="text" id="email" name="email" class="form-control pr-2" required="required">
                                </section>
                                <section class="form-group ">
                                    <label for="phone"><h5>شماره تماس </h5></label>
                                    <input type="text" id="phone" name="phone" class="form-control pr-2" required="required">
                                </section>
                                <section class="form-group">
                                    <label for="password"><h5>رمز عبور </h5></label>
                                    <input type="text" id="password" name="password" class="form-control pr-2" required="required">
                                </section>

                                <button type="submit" class="btn btn-primary btn-block">ورود</button>
                                <section class=" mt-4 text-center">
                                    <p>قبلا ثبت نام کرده اید؟ <a href="login.php">ورود</a> </p>
                                </section>

                            </form>
                        </section>
                    </section>
                </section>
            </section>
        </section>
    </section>
    <hr>
    <section class="container-fluid ">
        <section class="row ">
            <section class=" col-8 offset-2 mt-3">
                <footer class="text-dark text-center">
                    <p>Copyright &copy; 2019 Blessing.com<p>
                </footer>
            </section>
        </section>
    </section>
@endsection
@section('js')

@endsection