routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('show');



Auth::routes();

Route::middleware('auth')->prefix('administrator')->group(function (){
    Route::get('/admin', 'AdminController@index')->name('admin');
    Route::resource('/Contact','ContactController');
    Route::resource('/Gallery','GalleryController');
    Route::resource('/News','NewsController');
    Route::resource('/Slider','SliderController');
    Route::resource('/Setting','SettingController');
    Route::resource('/About','AboutController');
});

Route::post('/insertContact','ContactController@store')->name('Contact.Data');

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\createSliderRequest;
use App\Slider;
use Illuminate\Http\Request;
use phpDocumentor\Reflection\DocBlock\Description;

class SliderController extends Controller
{

    public function index()
    {
        $show_slider = Slider::all();
        return view('slider.index',compact('show_slider'));
    }


    public function create()
    {
        return view('slider.create');
    }


    public function store(createSliderRequest $request)
    {

        $slider = new Slider();

        $slider->name=$request->name;

        $file_slider = $request->file('image');
        if (!empty($file_slider)){
            $image=time().$file_slider->getClientOriginalName();
            $file_slider->move('images/slider',$image);
            $slider->image=$image;
        }
        $slider->status=$request->status;
        $slider->save();
        return redirect()->route('Slider.index');

    }



    public function show(Slider $slider)
    {
        //
    }


    public function edit($slider)
    {
        $slider_edit = Slider::findOrFail($slider);
        return view('slider.edit' , compact('slider_edit'));
    }


    public function update(Request $request, $slider)
    {
        $slider=Slider::findOrFail($slider);

        $slider->name=$request->name;

        $file_slider = $request->file('image');
        if (!empty($file_slider)){
            $imageDelete = $slider->image;
            unlink("images/slider/".$imageDelete);
            $image=time().$file_slider->getClientOriginalName();
            $file_slider->move('images/slider',$image);
            $slider->image=$image;
        }
        $slider->status=$request->status;
        $slider->save();

        return redirect()->route('Slider.index');
    }


    public function destroy($slider)
    {
        $slider = Slider::findOrFail($slider);
        unlink('images/slider/' . $slider->image);
        $slider->delete();
        session()->flash('delete','عملیات پاک کردن دیتا با موفقیت انجام شد');
        return back();
    }
}

resources/views/slider/create.blade.php
@extends('layouts.layout')
@section('css')
    <title> ارتباط با ما</title>
@endsection
@section('content')
    @if($errors->any())
        <section class="alert alert-danger col-8 offset-2 mt-5">
            @foreach($errors->all() as $item)
                <h4 class="text-center">{{$item}} </h4>
            @endforeach
        </section>
    @endif
    <section class="container mt-5">
        <section class="col-6 offset-3 " style="text-align: right">
            {{ Form::open(['route'=>'Slider.store' , 'method'=>'post','files'=>true]) }}
            <section class="form-group">
                {{ Form::label('name','عنوان',['class'=>'text-right d-block '])}}

                {{ Form::text('name' , null ,['class'=>'form-control text-right' , 'style'=>'border: 2px inset blue'])}}

            </section>

            <section class="form-group">
                {{Form::label('image','عکس',['class'=>'text-right d-block '])}}
                {{Form::file('image',['class'=>'form-control','style'=>'border: 2px inset blue'])}}
            </section>

            <section class="form-group">
                {{Form::label('status','وضعیت نمایش')}}
                {{Form::number('status',null,['class'=>'form-control', 'style'=>'border: 2px inset blue'])}}
            </section>

            <input type="submit" value="save" class="btn btn-warning btn-block">

            {{ Form::close() }}
        </section>
    </section>
@endsection

resources/views/slider/edit.blade.php
@extends('layouts.layout')
@section('css')
    <title> اسلایدرا</title>
@endsection
@section('content')
    <section class="container mt-5">
        <section class="col-6 offset-3 " style="text-align: right">
            {{ Form::model($slider_edit,['route'=>['Slider.update' ,$slider_edit->id], 'method'=>'PUT','files'=>true]) }}
            <section class="form-group">
                {{ Form::label('name','عنوان',['class'=>'text-right d-block '])}}

                {{ Form::text('name' , null ,['class'=>'form-control text-right' , 'style'=>'border: 2px inset blue'])}}

            </section>

            <section class="form-group">
                {{Form::label('image','عکس',['class'=>'text-right d-block '])}}
                {{Form::file('image',['class'=>'form-control','style'=>'border: 2px inset blue'])}}
                <img src="{{asset('images/slider/'.$slider_edit->image)}}" width="50px" height="50px">
            </section>

            <section class="form-group">
                {{Form::label('status','وضعیت نمایش')}}
                {{Form::number('status',null,['class'=>'form-control', 'style'=>'border: 2px inset blue'])}}
            </section>

            <input type="submit" value="save" class="btn btn-warning btn-block">

            {{ Form::close() }}
        </section>
    </section>
@endsection

resources/views/slider/index.blade.php
@extends('layouts.layout')
@section('css')
    <title>ارتباط با ما</title>

@endsection
@section('content')
    @if(session('delete'))
        <section class="col-6 offset-3 alert bg-success">
            <h3 class="text-info text-center">{{ session('delete') }}</h3>
        </section>
    @endif
    <section class="mt-3 pt-3 text-center">
        <a  class="btn btn-dark text-danger" href="{{ route('admin') }}">Dashbord</a>
        <a  class="btn btn-dark text-danger" href="{{route('Slider.create')}}">NEW</a>
    </section>
    <section class="container mt-5">
        <table class="table table-hover table-dark ">
            <thead>
            <tr>
                <th>id</th>
                <th>title</th>
                <th>image</th>
                <th>active</th>
                <th>delete</th>
                <th>update</th>
                <th>created_at</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($show_slider as $item)
                <tr>
                    <td>{{ $item->id }} </td>
                    <td>{{ $item->name }} </td>
                    <td><img src="{{asset('images/slider/'. $item->image) }}" width="50px" height="50px"></td>
                    <td>
                        @if ( $item->status  == 0)
                            <span class="badge badge-danger">غیرفعال</span>
                        @else
                            <span class="badge badge-success">فعال</span>
                        @endif
                    </td>
                    <td>
                        {{ Form::open(['route'=>['Slider.destroy', $item ->id],'method'=>'delete']) }}

                        {{Form::submit('حذف',['class'=>'btn-outline-danger'])}}

                        {{ Form::close() }}
                    </td>
                    <td>
                        {{--
                                            <a href="{{ route('News.edit', $item ->id) }}" >update</a>
                        --}}
                        <form method="GET" action="{{ route('Slider.edit', $item ->id) }}">
                            @csrf
                            <input type="submit"  class="btn-outline-primary" value="update">
                        </form>
                    </td>
                    <td>{{ \Hekmatinasser\Verta\Verta::instance($item->created_at) }} </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </section>
@endsection
@section('js')

@endsection