routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('show');



Auth::routes();

Route::middleware('auth')->prefix('administrator')->group(function (){
    Route::get('/admin', 'AdminController@index')->name('admin');
    Route::resource('/Contact','ContactController');
    Route::resource('/Gallery','GalleryController');
    Route::resource('/News','NewsController');
    Route::resource('/Slider','SliderController');
    Route::resource('/Setting','SettingController');
    Route::resource('/About','AboutController');
});

Route::post('/insertContact','ContactController@store')->name('Contact.Data');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    //
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\createNewsRequest;
use App\News;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class NewsController extends Controller
{

    public function index()
    {
        $select = News::all();
        return view('News.index',compact('select'));
    }


    public function create()
    {
        return view('News.create');
    }


    public function store(createNewsRequest $request)
    {
        $news = new News();
        $news->title = $request->title;
        $news->summary = $request->summary;
        $news->description = $request->description;

        $file_news = $request->file('image');
        if (!empty($file_news)){
            $image=time().$file_news->getClientOriginalName();
            $file_news->move('images/news',$image);
            $news->image=$image;
        }

        $news->meta_description = $request->meta_description;
        $news->meta_keywords = $request->meta_keywords;

        if ($request->slug) {
            $news->slug =makeSlug($request->slug);
        }else{
            $news->slug =makeSlug($request->title);
        }

        $news->status = $request->status;

        $news->save();

        return redirect()->route('News.index');
    }

    public function show(News $news)
    {
        //
    }


    public function edit($news)
    {
       $news_edit = News::findOrFail($news);
       return view('News.edit',compact('news_edit'));
    }


    public function update(Request $request, $news)
    {
        $news = News::findOrFail($news);
        $news->title = $request->title;
        $news->summary = $request->summary;
        $news->description = $request->description;
        $file_news = $request->file('image');
        if (!empty($file_news)){
            $imageDelete = $news->image;
            unlink("images/news/".$imageDelete);
            $image=time().$file_news->getClientOriginalName();
            $file_news->move('images/news/',$image);
            $news->image=$image;
        }
        $news->status = $request->status;
        $news->save();
        return redirect()->route('News.index');
    }


    public function destroy($news)
    {
        $news = News::where('id',$news)->first();
        unlink('images/news/' . $news->image);
        $news->delete();
        return back();
    }
}

resources/views/news/create.blade.php
@extends('layouts.layout')
@section('css')
    <title> ایجاد خبر</title>
@endsection
@section('content')
    @if($errors->any())
        <section class="alert alert-danger col-8 offset-2 mt-5">
            @foreach($errors->all() as $item)
                <h4 class="text-center">{{$item}} </h4>
            @endforeach
        </section>
    @endif
    <section class="container mt-5">
    <section class="col-6 offset-3">
            {{ Form::open(['route'=>'News.store' , 'method'=>'post','files'=>true]) }}
            <section class="form-group">
                <label for="title">title</label>
                <input type="text" id="title" class="form-control" value="" name="title" style="border: 2px inset blue">
            </section>
            <section class="form-group">
                <label for="summary">summary</label>
                <input type="text" id="summary" class="form-control" value="" name="summary" style="border: 2px inset blue">
            </section>
            <section class="form-group">
                {{Form::label('image','عکس',['class'=>'text-right d-block '])}}
                {{Form::file('image',['class'=>'form-control','style'=>'border: 2px inset blue'])}}
            </section>

            <section class="form-group">
                <label for="description">description</label>
                <textarea id="description" class="form-control editor"name="description"  style="border: 2px inset blue; resize: none">
                </textarea>
            </section>
            <section class="form-group">
                <label for="meta_description">meta_description</label>
                <textarea id="meta_description" class="form-control editor"name="meta_description"  style="border: 2px inset blue; resize: none">
                </textarea>
            </section>
            <section class="form-group">
                <label for="meta_keywords">meta_keywords</label>
                <textarea id="meta_keywords" class="form-control editor"name="meta_keywords"  style="border: 2px inset blue; resize: none">
                </textarea>
            </section>
            <section class="form-group">
                <label for="slug">slug</label>
                <textarea id="slug" class="form-control editor"name="slug"  style="border: 2px inset blue; resize: none">
                </textarea>
            </section>
            <section class="form-group">
                <label for="status">status</label>
                <input type="number" id="status" class="form-control" name="status" style="border: 2px inset blue" >
            </section>

            <input type="submit" value="save" class="btn btn-warning btn-block">

        {{ Form::close() }}
    </section>
</section>
@endsection

resources/views/news/edit.blade.php
@extends('layouts.layout')
@section('css')
    <title> ایجاد خبر</title>
@endsection
@section('content')
    <section class="container mt-5">
        <section class="col-6 offset-3">
            {{ Form::model($news_edit,['route'=>['News.update' ,$news_edit->id], 'method'=>'PUT','files'=>true]) }}

                <section class="form-group">
                    <label for="title">title</label>
                    <input type="text" id="title" class="form-control" value="{{ $news_edit->title }}" name="title" style="border: 2px inset blue">
                </section>
                <section class="form-group">
                    <label for="summary">summary</label>
                    <input type="text" id="summary" class="form-control" value="{{ $news_edit->summary }}" name="summary" style="border: 2px inset blue">
                </section>
                <section class="form-group">
                    {{Form::label('image','عکس',['class'=>'text-right d-block '])}}
                    {{Form::file('image',['class'=>'form-control','style'=>'border: 2px inset blue'])}}
                    <img src="{{asset('images/news/'.$news_edit->image)}}" width="50px" height="50px">
                </section>
                <section class="form-group">
                    <label for="description">description</label>
                    <textarea id="description" class="form-control editor"name="description"  style="border: 2px inset blue; resize: none">{{$news_edit->description}}
                </textarea>
                </section>
                <section class="form-group">
                    <label for="status">status</label>
                    <input type="number" id="status" class="form-control" name="status" value="{{$news_edit->status}}" style="border: 2px inset blue" >
                </section>
                <input type="submit" value="save" class="btn btn-warning btn-block">

            {{ Form::close() }}
        </section>
    </section>
@endsection

resources/views/news/index.blade.php
@extends('layouts.layout')
@section('css')
    <title>خبر ها</title>

@endsection
@section('content')
    <section class="mt-3 pt-3 text-center">
        <a  class="btn btn-dark text-danger" href="{{ route('admin') }}">Dashbord</a>
        <a  class="btn btn-dark text-danger" href="{{ route('News.create') }}">NEW</a>
    </section>
    <section class="container mt-5">
        <table class="table table-hover table-dark ">
            <thead>
            <tr>
                <th>id</th>
                <th>title</th>
                <th>image</th>
                <th>summary</th>
                <th>active</th>
                <th>delete</th>
                <th>update</th>
                <th>created_at</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($select as $item)
            <tr>
                <td>{{ $item->id }} </td>
                <td>{{ $item->title }} </td>
                <td><img src="{{asset('images/news/'. $item->image) }}" width="50px" height="50px"></td>
                <td>{{ $item->summary }} </td>
                <td>
                    @if ( $item->status  == 0)
                    <span class="badge badge-danger">غیرفعال</span>
                    @else
                    <span class="badge badge-success">فعال</span>
                    @endif
                </td>
                <td>
                    <form method="post" action="{{ route('News.destroy', $item ->id) }}">
                        @csrf
                        @method('delete')
                        <input type="submit"  class="btn-outline-danger" value="delete">
                    </form>
                </td>
                <td>
{{--
                    <a href="{{ route('News.edit', $item ->id) }}" >update</a>
--}}
                    <form method="GET" action="{{ route('News.edit', $item ->id) }}">
                        @csrf
                        <input type="submit"  class="btn-outline-primary" value="update">
                    </form>
                </td>
                <td>{{ \Hekmatinasser\Verta\Verta::instance($item->created_at) }} </td>
            </tr>
            @endforeach
            </tbody>
        </table>
    </section>
@endsection
@section('js')

@endsection